version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: platform_domain_schema
    ports:
      - 5432:5432
    networks:
      schema_network:
        ipv4_address: 172.10.0.2

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      schema_network:
        ipv4_address: 172.10.0.3

  rabbit:
    ports:
      - "127.0.0.1:5462:5432"
    networks:
      schema_network:
        ipv4_address: 172.10.0.4
    image: "rabbitmq:3-management"

  domain_worker:
    networks:
      schema_network:
        ipv4_address: 172.10.0.5
    build: 
      context: .
      dockerfile: Dockerfile.domain_worker
    depends_on:
      - 'postgres'
      - 'rabbit'
    environment:
      - POSTGRES=postgres

networks:
  schema_network:
    ipam:
      config:
        - subnet: 172.10.0.0/24
