version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      schema_network:
        ipv4_address: 172.10.0.2

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      schema_network:
        ipv4_address: 172.10.0.3

networks:
  schema_network:
    ipam:
      config:
        - subnet: 172.10.0.0/24
